/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login.home;

/**
 *
 * @author Giuseppe
 */
public class AggiornaDatiProcuratore extends javax.swing.JFrame {
    Controller c6;
    public AggiornaDatiProcuratore(Controller theController) {
        c6 = theController;
        this.setLocationRelativeTo(null);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputInserimentoMatricolaJTF = new javax.swing.JTextField();
        cercaMatricolaJB = new javax.swing.JToggleButton();
        inserimentoMatricolaJL = new javax.swing.JLabel();
        matricolaJL = new javax.swing.JLabel();
        codiceFiscaleJL = new javax.swing.JLabel();
        nomeJL = new javax.swing.JLabel();
        cognomeJL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cittaNascitaJL = new javax.swing.JLabel();
        viaJL = new javax.swing.JLabel();
        cittaResidenzaJL = new javax.swing.JLabel();
        capJL = new javax.swing.JLabel();
        ibanJL = new javax.swing.JLabel();
        modificaMatricolaJTF = new javax.swing.JTextField();
        modificaCodiceFiscaleJTF = new javax.swing.JTextField();
        modificaNomeJTF = new javax.swing.JTextField();
        modificaCognomeJTF = new javax.swing.JTextField();
        modificaDataNascitaJTF = new javax.swing.JTextField();
        modificaCittaNascitaJTF = new javax.swing.JTextField();
        modificaViaJTF = new javax.swing.JTextField();
        modificaCittaResidenzaJTF = new javax.swing.JTextField();
        modificaCapJTF = new javax.swing.JTextField();
        modificaIbanJTF = new javax.swing.JTextField();
        aggiornaDatiProcuratoreJB = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputInserimentoMatricolaJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputInserimentoMatricolaJTFActionPerformed(evt);
            }
        });

        cercaMatricolaJB.setText("CERCA");
        cercaMatricolaJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cercaMatricolaJBActionPerformed(evt);
            }
        });

        inserimentoMatricolaJL.setText("MATRICOLA DA CERCARE");

        matricolaJL.setText("Codice ID");

        codiceFiscaleJL.setText("Codice Fiscale");

        nomeJL.setText("Nome");

        cognomeJL.setText("Cognome");

        jLabel5.setText("Data di Nascita");

        cittaNascitaJL.setText(" Città di Nascita");

        viaJL.setText("Via");

        cittaResidenzaJL.setText("Città Residenza");

        capJL.setText("CAP");

        ibanJL.setText("IBAN");

        aggiornaDatiProcuratoreJB.setText("AGGIORNA");
        aggiornaDatiProcuratoreJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiornaDatiProcuratoreJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inserimentoMatricolaJL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputInserimentoMatricolaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cercaMatricolaJB))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(codiceFiscaleJL)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(modificaCodiceFiscaleJTF))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(matricolaJL)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(modificaMatricolaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(ibanJL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(modificaIbanJTF))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(capJL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(modificaCapJTF))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(cittaResidenzaJL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(modificaCittaResidenzaJTF))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(viaJL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(modificaViaJTF))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(cittaNascitaJL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(modificaCittaNascitaJTF))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(modificaDataNascitaJTF)))
                                        .addGap(39, 39, 39))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cognomeJL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(modificaCognomeJTF))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(nomeJL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(modificaNomeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(aggiornaDatiProcuratoreJB)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputInserimentoMatricolaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inserimentoMatricolaJL)
                    .addComponent(cercaMatricolaJB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matricolaJL)
                    .addComponent(modificaMatricolaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codiceFiscaleJL)
                    .addComponent(modificaCodiceFiscaleJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeJL)
                    .addComponent(modificaNomeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cognomeJL)
                    .addComponent(modificaCognomeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(modificaDataNascitaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cittaNascitaJL)
                    .addComponent(modificaCittaNascitaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viaJL)
                    .addComponent(modificaViaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cittaResidenzaJL)
                    .addComponent(modificaCittaResidenzaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capJL)
                    .addComponent(modificaCapJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibanJL)
                    .addComponent(modificaIbanJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(aggiornaDatiProcuratoreJB)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputInserimentoMatricolaJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputInserimentoMatricolaJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputInserimentoMatricolaJTFActionPerformed

    private void aggiornaDatiProcuratoreJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiornaDatiProcuratoreJBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aggiornaDatiProcuratoreJBActionPerformed

    private void cercaMatricolaJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cercaMatricolaJBActionPerformed
      c6.aggiornaProcuratore(inputInserimentoMatricolaJTF.getText());
    }//GEN-LAST:event_cercaMatricolaJBActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton aggiornaDatiProcuratoreJB;
    private javax.swing.JLabel capJL;
    private javax.swing.JToggleButton cercaMatricolaJB;
    private javax.swing.JLabel cittaNascitaJL;
    private javax.swing.JLabel cittaResidenzaJL;
    private javax.swing.JLabel codiceFiscaleJL;
    private javax.swing.JLabel cognomeJL;
    private javax.swing.JLabel ibanJL;
    private javax.swing.JTextField inputInserimentoMatricolaJTF;
    private javax.swing.JLabel inserimentoMatricolaJL;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel matricolaJL;
    private javax.swing.JTextField modificaCapJTF;
    private javax.swing.JTextField modificaCittaNascitaJTF;
    private javax.swing.JTextField modificaCittaResidenzaJTF;
    private javax.swing.JTextField modificaCodiceFiscaleJTF;
    private javax.swing.JTextField modificaCognomeJTF;
    private javax.swing.JTextField modificaDataNascitaJTF;
    private javax.swing.JTextField modificaIbanJTF;
    private javax.swing.JTextField modificaMatricolaJTF;
    private javax.swing.JTextField modificaNomeJTF;
    private javax.swing.JTextField modificaViaJTF;
    private javax.swing.JLabel nomeJL;
    private javax.swing.JLabel viaJL;
    // End of variables declaration//GEN-END:variables
}
