
package Login.home;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JTable;

public class SezioneProcuratori extends javax.swing.JFrame {
    
    AdminPage a1;
    Controller c2;
    
    public SezioneProcuratori(Controller theController) {
        initComponents();
        this.setLocationRelativeTo(null);
        c2 = theController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        modificareDatiProcuratoreJB = new javax.swing.JButton();
        aggiungereProcuratoreJB = new javax.swing.JButton();
        eliminaProcuratoreJB = new javax.swing.JButton();
        cercareProcuratoreJB = new javax.swing.JButton();
        tornaIndietroJB = new javax.swing.JButton();
        visualizzaDatiProcuratoriJB = new javax.swing.JButton();
        modificaCredenzialiJB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Unispace", 2, 14)); // NOI18N
        jLabel1.setText("GESTIONE DEI PROCURATORI NEL SISTEMA");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "code_id", "codice_fiscale", "nome", "iban"
            }
        ));
        jTable1.setToolTipText("");
        jScrollPane1.setViewportView(jTable1);

        modificareDatiProcuratoreJB.setText("Modifica i dati");
        modificareDatiProcuratoreJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificareDatiProcuratoreJBActionPerformed(evt);
            }
        });

        aggiungereProcuratoreJB.setText("Aggiungi un procuratore");
        aggiungereProcuratoreJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiungereProcuratoreJBActionPerformed(evt);
            }
        });

        eliminaProcuratoreJB.setText("Elimina Procuratore");
        eliminaProcuratoreJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaProcuratoreJBActionPerformed(evt);
            }
        });

        cercareProcuratoreJB.setText("Cerca Procuratore");
        cercareProcuratoreJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cercareProcuratoreJBActionPerformed(evt);
            }
        });

        tornaIndietroJB.setText("TORNA INDIETRO");
        tornaIndietroJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tornaIndietroJBActionPerformed(evt);
            }
        });

        visualizzaDatiProcuratoriJB.setText("VISUALIZZA TUTTI I PROCURATORI");
        visualizzaDatiProcuratoriJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizzaDatiProcuratoriJBActionPerformed(evt);
            }
        });

        modificaCredenzialiJB.setText("MODIFICA CREDENZIALI");
        modificaCredenzialiJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaCredenzialiJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aggiungereProcuratoreJB)
                        .addGap(62, 62, 62)
                        .addComponent(modificareDatiProcuratoreJB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(eliminaProcuratoreJB)
                        .addGap(65, 65, 65)
                        .addComponent(cercareProcuratoreJB))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(visualizzaDatiProcuratoriJB)
                        .addGap(79, 79, 79)
                        .addComponent(modificaCredenzialiJB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tornaIndietroJB)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificareDatiProcuratoreJB)
                    .addComponent(aggiungereProcuratoreJB)
                    .addComponent(eliminaProcuratoreJB)
                    .addComponent(cercareProcuratoreJB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tornaIndietroJB)
                    .addComponent(visualizzaDatiProcuratoriJB)
                    .addComponent(modificaCredenzialiJB))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tornaIndietroJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tornaIndietroJBActionPerformed
       c2.tornaIndietro();
    }//GEN-LAST:event_tornaIndietroJBActionPerformed

    private void aggiungereProcuratoreJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiungereProcuratoreJBActionPerformed
        c2.apriInserireNuovoProcuratore();
    }//GEN-LAST:event_aggiungereProcuratoreJBActionPerformed

    private void visualizzaDatiProcuratoriJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizzaDatiProcuratoriJBActionPerformed
        Statement stmt = null;
        ConnectionToDataBase db1 = new ConnectionToDataBase();
        Connection connct1 = db1.connectionToDatabase();
            
            try{
                
                stmt = connct1.createStatement();
                ResultSet rs = stmt.executeQuery("select * from procuratori_tbl");
                
                while(rs.next()){
                    
                    String id = rs.getString("code_id");
                    String codiceFiscale = rs.getString("codice_fiscale");
                    String nome = rs.getString("nome");
                    String iban = rs.getString("iban");
                    
                    //Array di stringhe per inserire i dati nella jtable
                    String tbData[]= {id, codiceFiscale, nome, iban};
                    DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                    //Aggiungiamo ogni stringa dell'array nella jtable
                    tblModel.addRow(tbData);
                }
                rs.close();
                stmt.close();
                connct1.close();
                
            }catch(Exception e){
                
                System.out.println("Errore nella stampa ");
                System.exit(0);
                
            }
    }//GEN-LAST:event_visualizzaDatiProcuratoriJBActionPerformed

    private void eliminaProcuratoreJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaProcuratoreJBActionPerformed
      c2.apriFinestraEliminaProcuratore();
    }//GEN-LAST:event_eliminaProcuratoreJBActionPerformed

    private void modificareDatiProcuratoreJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificareDatiProcuratoreJBActionPerformed
        c2.apriFinestraAggiornaDatiProcuratore();
    }//GEN-LAST:event_modificareDatiProcuratoreJBActionPerformed

    private void cercareProcuratoreJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cercareProcuratoreJBActionPerformed
       c2.apriFinestraCercaProcuratore();
    }//GEN-LAST:event_cercareProcuratoreJBActionPerformed

    private void modificaCredenzialiJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificaCredenzialiJBActionPerformed
       c2.apriFinestraModificaCredenziali();
    }//GEN-LAST:event_modificaCredenzialiJBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aggiungereProcuratoreJB;
    private javax.swing.JButton cercareProcuratoreJB;
    private javax.swing.JButton eliminaProcuratoreJB;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JButton modificaCredenzialiJB;
    private javax.swing.JButton modificareDatiProcuratoreJB;
    private javax.swing.JButton tornaIndietroJB;
    private javax.swing.JButton visualizzaDatiProcuratoriJB;
    // End of variables declaration//GEN-END:variables
}
