
package Login.home;

public class SezioneProcuratori extends javax.swing.JFrame {
    
    AdminPage a1;
    Controller c2;
    
    public SezioneProcuratori(Controller theController) {
        initComponents();
        this.setLocationRelativeTo(null);
        c2 = theController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        modificareDatiProcuratoreJB = new javax.swing.JButton();
        aggiungereProcuratoreJB = new javax.swing.JButton();
        eliminaProcuratoreJB = new javax.swing.JButton();
        cercareProcuratoreJB = new javax.swing.JButton();
        tornaIndietroJB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Unispace", 2, 14)); // NOI18N
        jLabel1.setText("GESTIONE DEI PROCURATORI NEL SISTEMA");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        modificareDatiProcuratoreJB.setText("Modifica i dati");

        aggiungereProcuratoreJB.setText("Aggiungi un procuratore");

        eliminaProcuratoreJB.setText("Elimina Procuratore");

        cercareProcuratoreJB.setText("Cerca Procuratore");

        tornaIndietroJB.setText("TORNA INDIETRO");
        tornaIndietroJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tornaIndietroJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aggiungereProcuratoreJB)
                        .addGap(62, 62, 62)
                        .addComponent(modificareDatiProcuratoreJB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(eliminaProcuratoreJB)
                        .addGap(65, 65, 65)
                        .addComponent(cercareProcuratoreJB))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tornaIndietroJB)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificareDatiProcuratoreJB)
                    .addComponent(aggiungereProcuratoreJB)
                    .addComponent(eliminaProcuratoreJB)
                    .addComponent(cercareProcuratoreJB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(tornaIndietroJB)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tornaIndietroJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tornaIndietroJBActionPerformed
       c2.tornaIndietro();
    }//GEN-LAST:event_tornaIndietroJBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aggiungereProcuratoreJB;
    private javax.swing.JButton cercareProcuratoreJB;
    private javax.swing.JButton eliminaProcuratoreJB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificareDatiProcuratoreJB;
    private javax.swing.JButton tornaIndietroJB;
    // End of variables declaration//GEN-END:variables
}
